### ISSUE TITLE
Clean-up

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/docs#205]
Currently, there is code in the documentation that is not required. The purpose of this issue is to remove this code but first verify if this code is being elsewhere and if it can be safely removed. The code that needs to be removed:
- [x] Folder `src/built_ins`
- [x] Folder `src/css`
- [ ] Versions older than `3.10.0`
- [x] Changelog older than `1.0.0`

**Comment by shay2025** [comment]
@ferreiratiago if we are removing the versions older than 3.10.0, shouldn't we also remove the changelogs older than 3.10.0?

**Comment by shay2025** [comment]
After discussion with @ferreiratiago, it was agreed that, for now, instead of removing all versions older than 3.10.0, all versions older than 3.23.0 would be removed from the versions sidebar and they would be mentioned on a new page that would contain all the versions. This page will be mentioned on the versions sidebar by `All versions`.
